name: Chat Keepalive

on:
  schedule:
    - cron: '*/10 * * * *'    # every 10 minutes
  workflow_dispatch:          # allow manual run from the Actions tab

permissions:
  contents: read

jobs:
  ping-chat:
    runs-on: ubuntu-latest
    steps:
      - name: POST to internal keepalive endpoint
        run: |
          curl -sS -o /dev/null -w "HTTP %{http_code}\n" \
            -X POST "https://https://terminal-chat-backend-tesla77.onrender.com/internal/keepalive" \
            -H "x-keepalive-token: ${CHAT_TOKEN}"
        env:
          CHAT_TOKEN: ${{ secrets.CHAT_KEEPALIVE_TOKEN }}
