name: Todo Keepalive
on:
  schedule:
    - cron: '*/7 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ping-todo:
    runs-on: ubuntu-latest
    steps:
      - name: PUT dummy task (touches Redis via controller)
        run: |
          set -e
          URL="https://todolist-xdzk.onrender.com/api/v1/tasks/${TODO_TASK_ID}"
          echo "Hitting: $URL"
          for i in 1 2 3; do
            code=$(curl -sS --max-time 20 -o resp.txt -w "%{http_code}" \
              -X PUT "$URL" \
              -H "Authorization: Bearer ${TODO_JWT}" \
              -H "Content-Type: application/json" \
              -d '{"is_completed": true}')
            echo "Attempt $i -> HTTP $code"
            if [ "$code" -ge 200 ] && [ "$code" -lt 300 ]; then
              echo "Success"
              exit 0
            fi
            sleep 5
          done
          echo "---- Response (first 300 bytes) ----"
          head -c 300 resp.txt || true
          exit 1
        env:
          TODO_JWT: ${{ secrets.TODO_KEEPALIVE_JWT }}
          TODO_TASK_ID: ${{ secrets.TODO_KEEPALIVE_TASK_ID }}
